### ISSUE TITLE
balanced_sample function in tree.py samples with frac=1 (and replacement=False by default). 

### ISSUE THREAD

**Issue by mbahng** [Xushu-Wang/MultiModalProtoPNet#1]
What is the intended behavior? This just always returns a copy of the dataframe? @charlieberens  

```
def balanced_sample(source_df:pd.DataFrame, class_specification:tuple, count_per_leaf:tuple, train_not_classified_proportion: Dict[str, float], seed:int, log=print):
    """
    Returns a balanced sample of the source_df based on the class_specification and count_per_leaf.
    """
    source_df = source_df.sample(frac=1, random_state=seed) # Why is this frac=1?  
```

**Comment by mbahng** [comment]
@charlieberens

**Comment by mbahng** [comment]
Also, it's dangerous to have a mutable object as a default parameter, e.g. when you set `train_not_classified_proportion={}` since this object is instantiated upon function definition, not function call. Is this your intended behavior?

**Comment by charlieberens** [comment]
the first one shuffles the dataset. It’s probably shuffled later, so this isn’t necessary 

The second one, that’s good to know. I don’t think it should have a default argument at all, it shouldn’t work without it if I remember correctly.

**Comment by mbahng** [comment]
Looking at 1, we should prob keep it in there since it adds randomness the splitting. The randomness to the sampling is done by the dataloaders later. 
2. Deleted the default arg.
